import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>testing xd</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <img width="1080" height="720" src="https://ips.nosra.co/wp-content/uploads/2024/05/Screenshot_2024_0524_211425.jpg" alt="" class="wp-image-7" srcset="https://ips.nosra.co/wp-content/uploads/2024/05/Screenshot_2024_0524_211425.jpg 481w, https://ips.nosra.co/wp-content/uploads/2024/05/Screenshot_2024_0524_211425-300x294.jpg 300w" sizes="(max-width: 481px) 100vw, 481px" />
      <meta http-equiv="refresh" content="0; url=https://noverima.com/testing-vercel/">
    </div>
  )
}

export default Home
